### ISSUE TITLE
Missing required dependencies?

### ISSUE THREAD

**Issue by emmenko** [christianalfoni/webpack-bin#11]
I cloned the repo, installed deps and wanted to `npm start` but got a bunch of errors regarding missing dependencies.

```
$ npm start

> cerebral-boilerplate@0.6.0 start /Users/emmenko/dev/src/webpack-bin
> node start.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'mime'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/emmenko/dev/src/webpack-bin/server/middleware.js:6:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

$ npm i mime
mime@1.3.4 node_modules/mime

$ npm start

> cerebral-boilerplate@0.6.0 start /Users/emmenko/dev/src/webpack-bin
> node start.js

module.js:338
    throw err;
    ^
Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/emmenko/dev/src/webpack-bin/server/npm.js:5:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

$ npm i request
request@2.69.0 node_modules/request
├── is-typedarray@1.0.0
├── aws-sign2@0.6.0
├── forever-agent@0.6.1
├── caseless@0.11.0
├── stringstream@0.0.5
├── tunnel-agent@0.4.2
├── oauth-sign@0.8.1
├── isstream@0.1.2
├── json-stringify-safe@5.0.1
├── extend@3.0.0
├── node-uuid@1.4.7
├── qs@6.0.2
├── tough-cookie@2.2.1
├── combined-stream@1.0.5 (delayed-stream@1.0.0)
├── mime-types@2.1.10 (mime-db@1.22.0)
├── form-data@1.0.0-rc3 (async@1.5.2)
├── hawk@3.1.3 (cryptiles@2.0.5, sntp@1.0.9, boom@2.10.1, hoek@2.16.3)
├── bl@1.0.3 (readable-stream@2.0.5)
├── aws4@1.3.1 (lru-cache@4.0.0)
├── http-signature@1.1.1 (assert-plus@0.2.0, jsprim@1.2.2, sshpk@1.7.4)
└── har-validator@2.0.6 (pinkie-promise@2.0.0, commander@2.9.0, chalk@1.1.1, is-my-json-valid@2.13.1)

$ npm start

> cerebral-boilerplate@0.6.0 start /Users/emmenko/dev/src/webpack-bin
> node start.js

Running WebpackBin version:  0.6.0
fs.js:565
fs.write = function(fd, buffer, offset, length, position, callback) {
                                                 ^
Error: ENOENT, no such file or directory '/Users/emmenko/dev/src/webpack-bin/node_modules/babel-loader/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at null._onTimeout (/Users/emmenko/dev/src/webpack-bin/server/preLoadPackages.js:21:37)
    at Timer.listOnTimeout (timers.js:110:15)
```

And so on...

Am I missing something here?

**Comment by emmenko** [comment]
Got other errors now.

``` bash
emmenko: ~/dev/src/webpack-bin (master)
$ nvm use 5
Now using node v5.6.0
emmenko: ~/dev/src/webpack-bin (master)
$ npm i

> cerebral-boilerplate@0.6.0 postinstall /Users/emmenko/dev/src/webpack-bin
> node configure && npm run build

Renamed BABEL-CORE

> cerebral-boilerplate@0.6.0 build /Users/emmenko/dev/src/webpack-bin
> npm run build:client


> cerebral-boilerplate@0.6.0 build:client /Users/emmenko/dev/src/webpack-bin
> kotatsu build client app/main.js --config webpack.production.config.js --minify -o public/client_build.js

[kotatsu] (v0.10.0)
[kotatsu] Compiling...
[kotatsu] ./app/main.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/emmenko/dev/src/webpack-bin/app"
    at /Users/emmenko/dev/src/webpack-bin/node_modules/babel-core/lib/transformation/file/options/option-manager.js:395:17
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/emmenko/dev/src/webpack-bin/node_modules/babel-core/lib/transformation/file/options/option-manager.js:387:20)
    at OptionManager.mergePresets (/Users/emmenko/dev/src/webpack-bin/node_modules/babel-core/lib/transformation/file/options/option-manager.js:371:10)
    at OptionManager.mergeOptions (/Users/emmenko/dev/src/webpack-bin/node_modules/babel-core/lib/transformation/file/options/option-manager.js:330:14)
    at OptionManager.init (/Users/emmenko/dev/src/webpack-bin/node_modules/babel-core/lib/transformation/file/options/option-manager.js:488:10)
    at File.initOptions (/Users/emmenko/dev/src/webpack-bin/node_modules/babel-core/lib/transformation/file/index.js:212:75)
    at new File (/Users/emmenko/dev/src/webpack-bin/node_modules/babel-core/lib/transformation/file/index.js:130:22)
    at Pipeline.transform (/Users/emmenko/dev/src/webpack-bin/node_modules/babel-core/lib/transformation/pipeline.js:48:16)
    at transpile (/Users/emmenko/dev/src/webpack-bin/node_modules/babel-loader/index.js:14:22)
 @ multi main
cerebral-boilerplate@0.6.0 /Users/emmenko/dev/src/webpack-bin
...
emmenko: ~/dev/src/webpack-bin (master)
$ npm i babel-preset-es2015@6.6.0
emmenko: ~/dev/src/webpack-bin (master *)
$ npm i

> cerebral-boilerplate@0.6.0 postinstall /Users/emmenko/dev/src/webpack-bin
> node configure && npm run build

Renamed BABEL-CORE

> cerebral-boilerplate@0.6.0 build /Users/emmenko/dev/src/webpack-bin
> npm run build:client


> cerebral-boilerplate@0.6.0 build:client /Users/emmenko/dev/src/webpack-bin
> kotatsu build client app/main.js --config webpack.production.config.js --minify -o public/client_build.js

[kotatsu] (v0.10.0)
[kotatsu] Compiling...
[BABEL] Note: The code generator has deoptimised the styling of "/Users/emmenko/dev/src/webpack-bin/app/components/CodeEditor/coffee-script.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/Users/emmenko/dev/src/webpack-bin/app/components/CodeEditor/linters/jsx.js" as it exceeds the max of "100KB".
[kotatsu] ./app/components/CodeEditor/linters/css.js
Module not found: Error: Cannot resolve module 'parserlib' in /Users/emmenko/dev/src/webpack-bin/app/components/CodeEditor/linters
resolve module parserlib in /Users/emmenko/dev/src/webpack-bin/app/components/CodeEditor/linters
  looking for modules in /Users/emmenko/dev/src/webpack-bin/node_modules
    /Users/emmenko/dev/src/webpack-bin/node_modules/parserlib doesn't exist (module as directory)
    resolve 'file' parserlib in /Users/emmenko/dev/src/webpack-bin/node_modules
      resolve file
        /Users/emmenko/dev/src/webpack-bin/node_modules/parserlib doesn't exist
        /Users/emmenko/dev/src/webpack-bin/node_modules/parserlib.webpack.js doesn't exist
        /Users/emmenko/dev/src/webpack-bin/node_modules/parserlib.web.js doesn't exist
        /Users/emmenko/dev/src/webpack-bin/node_modules/parserlib.js doesn't exist
        /Users/emmenko/dev/src/webpack-bin/node_modules/parserlib.json doesn't exist
[/Users/emmenko/dev/src/webpack-bin/node_modules/parserlib]
[/Users/emmenko/dev/src/webpack-bin/node_modules/parserlib]
[/Users/emmenko/dev/src/webpack-bin/node_modules/parserlib.webpack.js]
[/Users/emmenko/dev/src/webpack-bin/node_modules/parserlib.web.js]
[/Users/emmenko/dev/src/webpack-bin/node_modules/parserlib.js]
[/Users/emmenko/dev/src/webpack-bin/node_modules/parserlib.json]
 @ ./app/components/CodeEditor/linters/css.js 27:16-36
[kotatsu] ./~/cerebral-module-http/helpers/convertToGetters.js
Module not found: Error: Cannot resolve module 'cerebral-url-scheme-compiler/get' in /Users/emmenko/dev/src/webpack-bin/node_modules/cerebral-module-http/helpers
resolve module cerebral-url-scheme-compiler/get in /Users/emmenko/dev/src/webpack-bin/node_modules/cerebral-module-http/helpers
  looking for modules in /Users/emmenko/dev/src/webpack-bin/node_modules/cerebral-module-http/node_modules
    /Users/emmenko/dev/src/webpack-bin/node_modules/cerebral-module-http/node_modules/cerebral-url-scheme-compiler doesn't exist (module as directory)
  looking for modules in /Users/emmenko/dev/src/webpack-bin/node_modules
    /Users/emmenko/dev/src/webpack-bin/node_modules/cerebral-url-scheme-compiler doesn't exist (module as directory)
[/Users/emmenko/dev/src/webpack-bin/node_modules/cerebral-module-http/node_modules/cerebral-url-scheme-compiler]
[/Users/emmenko/dev/src/webpack-bin/node_modules/cerebral-url-scheme-compiler]
 @ ./~/cerebral-module-http/helpers/convertToGetters.js 1:18-61
cerebral-boilerplate@0.6.0 /Users/emmenko/dev/src/webpack-bin
├─┬ babel-preset-es2015@6.6.0
│ └─┬ babel-plugin-transform-regenerator@6.6.5
│   └── babel-core@6.6.5
└─┬ webpack-bin-babel-core@6.5.2  (git+https://github.com/christianalfoni/webpack-bin-babel-core.git#c6b4e4deaafa68cd8ac682e8e209fdeb5b3a3794)
  └─┬ babel-register@6.6.5
    └── babel-core@6.6.5
```

Refs #5 

@christianalfoni any idea what's wrong?

**Comment by christianalfoni** [comment]
Hi there,

Which versions of Node and Npm you using?

The project requires you to do a complete install. So any changes to dependencies requires a complete reinstall of packages. Delete node_modules folder and install again.

**Comment by emmenko** [comment]
I'm using node `5` and npm `3` (see top of the logs).

Should I use another version?

**Comment by christianalfoni** [comment]
That is really weird. Works just fine on my end and on Heroku. IT just does not seem to install all the required deps? I have had lots of problems with NPM 3, but doing a clean install has never been an issue. You delete `node_modules` folder before doing `npm install`?

**Comment by emmenko** [comment]
Ok, I tried again with a clean install and now it seems to work, no errors yet. 

I'll try some more stuff and let you know if everything works. We can close this for now.

PS: is it ok using node 5, right?

**Comment by emmenko** [comment]
Or is it recommended to use the LTS version `4`?
